# Generated by Django 4.1.7 on 2023-02-18 00:41

from django.db import migrations
from bookstore_api.models import User, CreditCard


def load_data(apps, schema_editor):
    # Create dummy User
    user = User.objects.create_user(username='dummy_user', password='password')
    user.name = 'Dummy User'
    user.email = 'dummyuser@example.com'
    user.home_address = '123 Main Street'
    user.save()

    # Create dummy CreditCard
    credit_card = CreditCard(user=user, card_number='1234567890123456', card_type='VISA', expiration_date='2023-01-01')
    credit_card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
